# METADATA
# This script is associated with the article 'COVID-19 among people experiencing homelessness in England: a modelling study'
# [ Add publication details ]
# This script includes the function 'run_model', which is the main function that runs a single iteration of the model
# There are also fixed parameters that are assigned to the global environment prior to defining the function. These are required to run the model
# An internet connection is required to read some of the inputs from GitHub
# Individuals are assumed to be in one of 16 discrete statuses, which are described in section 1, below
# Running the function 'run_model' will produce an integer matrix in which each row is an individual, each column is a day, and the cell value represents the status of the individual on that day
# For example: {m <- run_model()} will use the default model parameters and assign a matrix of size 46,565 x 120 to variable 'm'
# Other scripts interpet this output, run the model multiple times, and create results
# The script is written in R4.0.0 but is compatible with most recent versions of R

# -------------
# 1. STATUS KEY
# =============

# The model assumes that individuals are in one of 16 discrete statuses:

# 1 = community: susceptible
# 2 = community: exposed
# 3 = community: infectious pre-symptomatic
# 4 = community: infectious symptomatic
# 5 = community: not infectious symptomatic
# 6 = community: recovered

# 7 = PROTECT: susceptible
# 8 = PROTECT: exposed
# 9 = PROTECT: infectious pre-symptomatic
# 10 = PROTECT: infectious symptomatic (transferred to COVID-CARE next day)
# 11 = PROTECT: recovered

# 12 = CARE: infectious symptomatic
# 13 = CARE: not infectious symptomatic

# 14 = hospital
# 15 = ITU
# 16 = died

# -------------------
# 2. FIXED PARAMETERS
# ===================

# population size and clusters
# ----------------------------

# read variables giving cluster ID's. These variables are generated by the separate script 'assign_clusters.R'. There is no need to run this script.
# 'cl' = community cluster id's
# 'type' = location in the community (1 = hostel; 2 = night-shelter; 3 = sleeping outside)
# 'n' = total number of individuals in the model
# 'hotel_cl' = id for the COVID-PROTECT hotel that an individual would be transferred to, if they accept

load(url("https://github.com/maxeyre/Homeless-COVID-19/blob/master/model/INPUT_cluster_ids.RData?raw=TRUE"))

# background incidence
# --------------------

background_incidence <- read.csv("https://raw.githubusercontent.com/maxeyre/Homeless-COVID-19/master/model/INPUT_gp_cases31july2020.csv", colClasses = c('Date', rep('integer', 6)))
background_incidence$date <- NULL
gp_scenarios <- c('wave1_ons', 'wave1_mrc', 'wave1_low', 'wave2_sharp', 'wave2_flat')
background_incidence[, gp_scenarios] <- background_incidence[, gp_scenarios] / 56286961 # population of England (calculate daily incidence)

# discrete gamma distribution function
# ------------------------------------

rdg <- function(n, mu, k) as.integer(rgamma(n, shape = (mu-0.5)/k, scale = k)) + 1L

# -----------------
# 3. MODEL FUNCTION
# =================

run_model <- function(
  
  # ---------------------------------
  # inputs (values are base scenario)
  # ---------------------------------
  
  # basic parameters
  # ----------------
  
  seed = NA,
  model_duration = 365,
  gen_pop_mix_start = 1, # period 1 start. set to NA for the whole duration to be as per 'gen_pop_mix_para2'
  gen_pop_mix_end = 182, # period 1 end. set to NA for the whole duration to be as per 'gen_pop_mix_para2'
  gen_pop_mix_para = 0.5, # paramenter 'm' for period 1
  gen_pop_mix_para2 = 1, # parameter 'm' for period 2
  bi = 'wave1_ons', # relevant column header in object 'background_incidence'
  TEST = F, # test with one big cluster, no background incidence, and seeded with 10 exposed on day 1

  # intervention
  # ------------
  
  interventions_start = 29,
  intervention_ends = 182, # set to NA for intervention does not end
  dur.PROTECT_rec = 28, # PROTECT population recruited steadily over this period (days)
  accept_ss = 0.8, # proportion street sleepers PROTECT when offered
  accept_CARE = 0.8, # proportion accepting CARE when offered
  self_discharge_fortnight = 0.08, # assuming 8% risk of self-discharge over 2 weeks
  
  # disease 
  # -------
  
  # disease durations (these are the mean values; individual-level durations follow a discrete gamma distribution)
  dur.exposed = 4,
  dur.presymptom = 1.5,
  dur.infSymptom = 3.5,
  dur.hospital = 8,
  
  # dispersion of disease durations
  k.exposed = 4,
  k.presymptom = 4,
  k.infSymptom = 4,
  k.hospital = 8,
  
  # case fatality and hospitalisation rates
  covid_severity = c(0.4, 0.538, 0.044, 0.018), # asymptomatic / mild / moderate / severe. should sum to 1
  cfr = c(0, 0.0028, 0.15, 0.45), # by severity
  cfr_multiplier = 1, # used for sensitivity analyses
  
  # r0
  r0_h = 2.5, # hostel
  r0_ns_multiplier = 1.5, # night shelters = this value * r0_h
  r0_ss_multiplier = 0.75, # street sleeping = this value * r0_h
  r0_cp = 0.75, # COVID PROTECT
  suppress_start = 1,
  suppress_end = 182,
  suppressValue = 0.75,
  k = 1 # distribution of R0 values. Positive value. Set to NA for uniform values of R0. High values approximate to poisson distribution
  
) {
  
  # ----------------------
  # calculate model inputs 
  # ----------------------
  
  # seed
  if (!is.na(seed)) set.seed(seed)
  
  # daily self discharge risk
  self_discharge_risk <- 1-(1-self_discharge_fortnight)^(1/14)
  
  # SEIR values. 'period1' is specified by 'suppress_start' and 'suppress_end'
  r0_ns <- r0_h * r0_ns_multiplier
  r0_ss <- r0_h * r0_ss_multiplier
  r0i_period2 <- c(r0_h, r0_ns, r0_ss) # r0 community
  r0i_period2 <- r0i_period2[type] # average r0 by individual
  if (!is.na(k)) {r0i_period2 <- rnbinom(n, size = k, mu = r0i_period2)}  # r0 by individual after k parameter
  r0i_period1 <- if (is.na(k)) rep(suppressValue, n) else rnbinom(n, size = k, mu = suppressValue)
  suppressDays <- if (is.na(suppress_start)) NA else (suppress_start:suppress_end)
  r0i_cp <- if (is.na(k)) rep(r0_cp, n) else rnbinom(n, size = k, mu = r0_cp)
  g <- 1 / (dur.presymptom + dur.infSymptom) # gamma value in force of infection calculation
  
  # covid severity
  severity <- sample(seq_along(covid_severity), n, replace = T, prob = covid_severity)

  # case fatality rates
  cfri <- cfr[severity] * cfr_multiplier
  
  # PROTECT referral day
  PROTECT_referral_day <- sample(seq_len(dur.PROTECT_rec) + interventions_start - 1L, n, replace = T)

  # durations: individual 
  day.inf.i <- rdg(n, dur.exposed, k = k.exposed)
  day.sym.i <- rdg(n, dur.presymptom, k = k.presymptom) + day.inf.i
  day.adm.i <- rdg(n, dur.infSymptom, k = k.infSymptom) + day.sym.i # day infectiousness ends and/or hospitalised
  day.end.i <- rdg(n, dur.hospital, k = k.hospital) + day.adm.i # day disease ends (recovers or dies)

  # intervention ends
  ends <- min(model_duration, intervention_ends, na.rm = T)
  
  # general population incidence parameter
  gpm <- rep(gen_pop_mix_para2, model_duration)
  if (!is.na(gen_pop_mix_start)) {
    gpmSuppressDays <- gen_pop_mix_start:gen_pop_mix_end
    gpm[gpmSuppressDays] <- gen_pop_mix_para
  }
  inc <- background_incidence[seq_len(model_duration), bi]
  inc <- inc * gpm[seq_len(model_duration)]
  
  # TEST values
  cl <- if (TEST) rep(1, n) else cl
  inc <- if (TEST) rep(0, model_duration) else inc
  
  # ------------------------------------
  # function for modelling daily changes
  # ------------------------------------
  
  f <- function (day) {
    
    # previous statuses
    # -----------------
    
    sy <- dat[, day] # status yesterday
    
    # duration after COVID19 exposure (varying by individual)
    # -------------------------------------------------------
    
    q.inf <- (day - day.inf.i) == day_of_infection # becomes infectious today
    q.sym <- (day - day.sym.i) == day_of_infection # becomes symptomatic today
    q.CAR <- (day - day.sym.i) == (day_of_infection + 1) # offered COVID CARE
    q.adm <- (day - day.adm.i) == day_of_infection # becomes non-infections and/or admitted today
    q.end <- (day - day.end.i) == day_of_infection # recovers or dies today

    # location of individual yesterday
    # --------------------------------
    
    location <- findInterval(sy, c(0, 7, 12, 14)) # community, PROTECT, CARE, hospital/died
    cl2 <- ifelse(location == 2, hotel_cl, cl)
    cl2[location > 2] <- NA
    
    # force of infection by individual
    # --------------------------------
    
    # likelihood of mixing with infectious person
    iN <- tapply(sy, cl2, function(x) sum(x == 3 | x == 4) / sum(x < 7)) # proportion infectious in community by cluster
    iN <- iN[cl2] # i/N by individual
    iN[location == 2] <- sum(sy == 9 | sy == 10) / sum(location == 2) # COVID PROTECT
    
    # cluster-specific r0's
    r0i <- if (day %in% suppressDays) r0i_period1 else r0i_period2
    r0i <- ifelse(location == 2, r0i_cp, r0i) # set to relevant value for community cluster or COVID-PROTECT
    r0i[!(sy %in% c(3, 4, 9, 10))] <- NA
    r0c <- tapply(r0i, cl2, mean, na.rm = T) # community r0's by cluster - mean of infectious individuals
    r0c_indices <- as.integer(names(r0c))
    r0c_indices <- match(cl2, r0c_indices)
    r0f <- r0c[r0c_indices]
    
    # force of infection
    foi <- 1 - exp(-iN * g * r0f)
    foi[is.na(foi)] <- 0 # is.na includes is.nan (changing those with zero denominator to zero)
    
    # intervention open
    # -----------------
    
    started <- (day >= interventions_start) & (day <= ends)
    
    # probabilities
    # -------------
    
    p.cv1 <- rbinom(n, 1, foi) == 1 # # force of infection with homeless settings
    p.cv2 <- rbinom(n, 1, inc[day]) == 1 # background exposure
    p.dth <- rbinom(n, 1, cfri) == 1
    p.sdg <- rbinom(n, 1, self_discharge_risk) == 1 # self-discharge risk
    p.rCC <- (rbinom(n, 1, accept_CARE) == 1) & started & (severity != 1) # accept_ss COVID-CARE referral
    p.rCP <- (rbinom(n, 1, accept_ss) == 1) & started # street sleepers accept COVID-PROTECT referral
    p.rCP[type == 2] <- T
    p.rCP[type == 1] <- F
    
    # new status
    # ----------
    
    status <- sy
    
    # community
    status[(sy == 1) & (p.cv1 | p.cv2)] <- 2L
    status[location == 1 & q.inf] <- 3L
    status[location == 1 & q.sym] <- 4L
    status[location == 1 & q.adm] <- 5L
    status[location == 1 & q.CAR & p.rCC] <- 12L
    status <- ifelse((sy < 4) & (PROTECT_referral_day == day) & p.rCP, sy + 6L, status)
    
    # PROTECT 
    status[sy == 7 & p.cv1] <- 8L
    status[location == 2 & q.inf] <- 9L
    status[location == 2 & q.sym] <- 10L
    status[sy == 10] <- 12L # transferred to COVID-CARE (even if asymptomatic to reflect testing)
    status[sy == 7 & p.sdg] <- 1L # self-discharge
    status[sy == 11 & p.sdg] <- 6L # self-discharge
    status[sy == 7 & !started] <- 1L
    status[sy == 11 & !started] <- 6L
    
    # CARE
    status[location == 3 & q.adm] <- 13L
    status <- ifelse(location == 3 & p.sdg, sy - 8L, status) 

    # hospital admissions
    status[q.adm & (severity == 3)] <- 14L
    status[q.adm & (severity == 4)] <- 15L
    
    # end of covid
    status[q.end] <- 6L
    status[location == 3 & q.end & p.rCP & started] <- 11L
    status[q.end & p.dth] <- 16L
    
    return(status)
    
  }
  
  # ---------------
  # run daily model
  # ---------------
  
  dat <- matrix(rep(1L, n)) # day 0
  day_of_infection <- rep(-Inf, n)
  
  # seed (for TEST scenario)
  if (TEST) {dat[,1] <- rep(2:1, c(10, n - 10))}
  
  for(i in seq_len(model_duration)) {
    dat <- cbind(dat, f(i))
    day_of_infection[(dat[,i+1] %in% c(2, 8)) & (day_of_infection == -Inf)] <- i + 1
  }
  
  return(dat)
  
}
